#!/usr/bin/env sh

set -e

cd $(dirname $0) || exit 1

STATE_FILE="state.yaml"
ACCESS_KEY_FILE="access-key.yaml"


case $1 in
    bootstrap)
        export BUCKET_NAME="$(yq .stateBucket "${STATE_FILE}")"
        KEY_ID_KEY="$(yq .secretKeys.accessKeyId "${STATE_FILE}")"
        SECRET_KEY="$(yq .secretKeys.secretAccessKey "${STATE_FILE}")"

        export ACCESS_KEY_ID=$(yq ".${KEY_ID_KEY}" "${ACCESS_KEY_FILE}")
        export SECRET_ACCESS_KEY=$(yq ".${SECRET_KEY}" "${ACCESS_KEY_FILE}")

        envsubst <state.tf >.state.tf
        mv -f .state.tf state.tf
        ;;
    init)
        shift
        SECRET_KEY="$(yq .secretKeys.secretAccessKey "${STATE_FILE}")"
        export SECRET_ACCESS_KEY=$(yq ".${SECRET_KEY}" "${ACCESS_KEY_FILE}")
        terraform init -backend-config="secret_key=${SECRET_ACCESS_KEY}" $@
        ;;
    *)
        YC_TOKEN=$(./token) terraform $@
        ;;
esac
